include("/usr/share/cmake/Modules/GoogleTestAddTests.cmake")
gtest_discover_tests_impl(
  TEST_TARGET [==[idr_tests]==]
  TEST_EXECUTABLE [==[/home/levi/test/deadreckoning/dr_nav/app/src/main/cpp/build_test/idr_tests]==]
  TEST_EXECUTOR [==[]==]
  TEST_WORKING_DIR [==[/home/levi/test/deadreckoning/dr_nav/app/src/main/cpp/build_test]==]
  TEST_EXTRA_ARGS [==[]==]
  TEST_PROPERTIES [==[]==]
  TEST_PREFIX [==[]==]
  TEST_SUFFIX [==[]==]
  TEST_FILTER [==[]==]
  NO_PRETTY_TYPES [==[FALSE]==]
  NO_PRETTY_VALUES [==[FALSE]==]
  TEST_LIST [==[idr_tests_TESTS]==]
  CTEST_FILE [==[/home/levi/test/deadreckoning/dr_nav/app/src/main/cpp/build_test/idr_tests_e3b0c442_tests.cmake]==]
  TEST_DISCOVERY_TIMEOUT [==[5]==]
  TEST_DISCOVERY_EXTRA_ARGS [==[]==]
  TEST_XML_OUTPUT_DIR [==[]==]
  TEST_JSON_OUTPUT_DIR [==[/home/levi/test/deadreckoning/dr_nav/app/src/main/cpp/build_test]==]
)
